In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,DRIRC89L0T,18,137576,209136,846,26,2,10.47,60,0.81,High School,Self-employed,Single,Yes,No,Business,No,0
1,TS0FIUNHNU,47,57194,5970,748,30,2,19.72,36,0.73,High School,Unemployed,Divorced,No,Yes,Education,No,0
2,I0YR284A1V,26,84328,95065,453,7,2,24.25,12,0.45,Master's,Self-employed,Married,No,No,Other,Yes,0
3,WB1T7NQV8A,53,49795,229582,533,107,3,14.44,60,0.17,Bachelor's,Self-employed,Single,Yes,No,Auto,Yes,1
4,J6GU9M4G1Z,49,115450,22072,840,0,4,24.48,12,0.11,Bachelor's,Part-time,Single,No,Yes,Education,Yes,0

In [4]:
df.drop(columns="LoanID", inplace=True)
df

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,18,137576,209136,846,26,2,10.47,60,0.81,High School,Self-employed,Single,Yes,No,Business,No,0
1,47,57194,5970,748,30,2,19.72,36,0.73,High School,Unemployed,Divorced,No,Yes,Education,No,0
2,26,84328,95065,453,7,2,24.25,12,0.45,Master's,Self-employed,Married,No,No,Other,Yes,0
3,53,49795,229582,533,107,3,14.44,60,0.17,Bachelor's,Self-employed,Single,Yes,No,Auto,Yes,1
4,49,115450,22072,840,0,4,24.48,12,0.11,Bachelor's,Part-time,Single,No,Yes,Education,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204272,40,116623,161673,651,79,2,23.44,12,0.87,Bachelor's,Part-time,Divorced,No,No,Home,Yes,0
204273,67,62958,189499,460,77,3,9.29,36,0.11,Bachelor's,Self-employed,Single,No,No,Business,Yes,0
204274,62,34372,59645,524,94,3,9.72,60,0.24,PhD,Full-time,Single,Yes,No,Auto,No,0
204275,44,146262,198454,489,7,4,4.31,48,0.30,High School,Self-employed,Married,Yes,No,Home,No,0
204276,36,97844,188593,542,2,3,23.14,24,0.83,Bachelor's,Part-time,Divorced,No,No,Home,No,1

In [5]:
from sklearn.preprocessing import LabelEncoder

categorical_columns = ['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']
label_encoder = LabelEncoder()

for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

In [6]:
df.isna().sum()

Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [7]:
correlation = df.corr()
correlation['Default'].sort_values(ascending=False)

Default           1.000000
InterestRate      0.129885
LoanAmount        0.085519
EmploymentType    0.042670
NumCreditLines    0.028565
DTIRatio          0.018595
LoanTerm          0.000815
MaritalStatus    -0.008441
LoanPurpose      -0.010799
HasMortgage      -0.021174
Education        -0.021508
CreditScore      -0.034128
HasDependents    -0.034737
HasCoSigner      -0.040688
MonthsEmployed   -0.095429
Income           -0.100515
Age              -0.167484
Name: Default, dtype: float64

In [8]:
df['LoanAmtInterestRate'] = df['InterestRate'] * df['LoanAmount']
df

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default,LoanAmtInterestRate
0,18,137576,209136,846,26,2,10.47,60,0.81,1,2,2,1,0,1,0,0,2189653.92
1,47,57194,5970,748,30,2,19.72,36,0.73,1,3,0,0,1,2,0,0,117728.40
2,26,84328,95065,453,7,2,24.25,12,0.45,2,2,1,0,0,4,1,0,2305326.25
3,53,49795,229582,533,107,3,14.44,60,0.17,0,2,2,1,0,0,1,1,3315164.08
4,49,115450,22072,840,0,4,24.48,12,0.11,0,1,2,0,1,2,1,0,540322.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204272,40,116623,161673,651,79,2,23.44,12,0.87,0,1,0,0,0,3,1,0,3789615.12
204273,67,62958,189499,460,77,3,9.29,36,0.11,0,2,2,0,0,1,1,0,1760445.71
204274,62,34372,59645,524,94,3,9.72,60,0.24,3,0,2,1,0,0,0,0,579749.40
204275,44,146262,198454,489,7,4,4.31,48,0.30,1,2,1,1,0,3,0,0,855336.74
204276,36,97844,188593,542,2,3,23.14,24,0.83,0,1,0,0,0,3,0,1,4364042.02

In [9]:
df['Default'].value_counts()

Default
0    180524
1     23753
Name: count, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df.loc[:, 'Default'])

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, mean_squared_error

# Load dataset
df = pd.read_csv("train.csv")

# Preprocessing steps
df.drop(columns="LoanID", inplace=True)
categorical_columns = ['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']
label_encoder = LabelEncoder()
for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

# Create new feature
df['LoanAmtInterestRate'] = df['InterestRate'] * df['LoanAmount']

# Define features and target
X = df.drop(columns='Default')
y = df['Default']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Set up the pipeline with polynomial features and linear regression
pipeline = Pipeline([
    ('poly_features', PolynomialFeatures()),
    ('linear_regression', LinearRegression())
])

# Define parameter grid for degree of polynomial features
param_grid = {
    'poly_features__degree': [1, 2, 3],  # Degrees of polynomial features
    'linear_regression__fit_intercept': [True, False]
}

# Set up GridSearchCV
grid_search = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)

# Fit the model
grid_search.fit(X_train, y_train)

# Get the best model and evaluate
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Calculate accuracy or use other metrics like RMSE for regression
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error (RMSE):", rmse)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, mean_squared_error

# Load dataset
df = pd.read_csv("train.csv")

# Preprocessing steps
df.drop(columns="LoanID", inplace=True)
categorical_columns = ['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']
label_encoder = LabelEncoder()
for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

# Create new feature
df['LoanAmtInterestRate'] = df['InterestRate'] * df['LoanAmount']

# Define features and target
X = df.drop(columns='Default')
y = df['Default']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize and train the Gradient Boosting Classifier
gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train, y_train)

# Predict on the test set
y_pred = gb_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)

print(f"Gradient Boosting Model Accuracy: {accuracy}")
print(f"Gradient Boosting Model RMSE: {rmse}")

Gradient Boosting Model Accuracy: 0.8864059134521245
Gradient Boosting Model RMSE: 0.33703721834224104

/Users/ayusharyakashyap/Library/Python/3.11/lib/python/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, mean_squared_error

# Load dataset
df = pd.read_csv("train.csv")

# Preprocessing steps
df.drop(columns="LoanID", inplace=True)
categorical_columns = ['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']
label_encoder = LabelEncoder()
for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

# Create new feature
df['LoanAmtInterestRate'] = df['InterestRate'] * df['LoanAmount']

# Define features and target
X = df.drop(columns='Default')
y = df['Default']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize and train the Gradient Boosting Classifier
gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train, y_train)

# Predict on the test set
y_pred = gb_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)

print(f"Gradient Boosting Model Accuracy: {accuracy}")
print(f"Gradient Boosting Model RMSE: {rmse}")

# Prepare submission file based on sample_submission.csv format
# Assuming that 'LoanID' is part of the test set for submission

# Load test set with 'LoanID' for submission file
test_data = pd.read_csv("test.csv")  # Load test data separately for LoanID
test_data_preprocessed = test_data.drop(columns=['LoanID'])  # Drop 'LoanID' for prediction

# Apply the same preprocessing on the test_data
for col in categorical_columns:
    test_data_preprocessed[col] = label_encoder.transform(test_data_preprocessed[col])
test_data_preprocessed['LoanAmtInterestRate'] = test_data_preprocessed['InterestRate'] * test_data_preprocessed['LoanAmount']

# Predict on the entire test data
test_predictions = gb_model.predict(test_data_preprocessed)

# Create submission DataFrame
submission_df = pd.DataFrame({
    'LoanID': test_data['LoanID'],
    'Default': test_predictions
})

# Save to CSV
submission_df.to_csv("gradient_boosting_submission.csv", index=False)

Gradient Boosting Model Accuracy: 0.8864059134521245
Gradient Boosting Model RMSE: 0.33703721834224104

/Users/ayusharyakashyap/Library/Python/3.11/lib/python/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

ValueError: y contains previously unseen labels: 'PhD'

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# Load the data
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
sample_submission = pd.read_csv('sample_submission.csv')

# Separate features and target in training data
X = train_df.drop(columns=['Default'])
y = train_df['Default']

# Preprocessing
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

# Preprocessing pipelines
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', pd.get_dummies(drop_first=True))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Split the data into train and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the model pipeline with Gradient Boosting Classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', GradientBoostingClassifier(random_state=42))
])

# Train the model
model.fit(X_train, y_train)

# Validate the model
y_val_pred = model.predict(X_val)
accuracy = accuracy_score(y_val, y_val_pred)
print(f"Validation Accuracy: {accuracy:.4f}")

# Prepare the test set for predictions
X_test = test_df
predictions = model.predict(X_test)

# Prepare the submission file
submission = sample_submission.copy()
submission['Default'] = predictions
submission.to_csv('submission.csv', index=False)

print("Submission file created at submission.csv")

TypeError: get_dummies() missing 1 required positional argument: 'data'